#!/usr/bin/env python3
"""Generate cache-busted CSS for the AlgoPlasma home hero image.

The served image lives under ``source/_static/home`` because Sphinx copies
``_static`` files reliably.  A legacy copy under ``source/images/home`` is also
accepted: if it is newer, this script copies it into the served location.
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path


DOCS_DIR = Path(__file__).resolve().parents[1]
SOURCE_DIR = DOCS_DIR / "source"
SERVED_IMAGE = SOURCE_DIR / "_static" / "home" / "ap_pic_het_3d_hero.png"
LEGACY_IMAGE = SOURCE_DIR / "images" / "home" / "ap_pic_het_3d_hero.png"
TYPO_IMAGE = SOURCE_DIR / "images" / "home" / "ap_pic_het_3d_hero.png.png"
GENERATED_CSS = SOURCE_DIR / "_static" / "ap-home-hero.css"


def newest_existing(paths: list[Path]) -> Path | None:
    existing = [path for path in paths if path.exists()]
    if not existing:
        return None
    return max(existing, key=lambda path: path.stat().st_mtime_ns)


def sha256_short(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()[:16]


def main() -> None:
    source_image = newest_existing([SERVED_IMAGE, LEGACY_IMAGE, TYPO_IMAGE])
    if source_image is None:
        raise SystemExit(
            "Home hero image is missing. Put it at "
            f"{SERVED_IMAGE.relative_to(DOCS_DIR)}"
        )

    SERVED_IMAGE.parent.mkdir(parents=True, exist_ok=True)
    if source_image != SERVED_IMAGE:
        shutil.copy2(source_image, SERVED_IMAGE)
        print(f"[home hero] copied {source_image.relative_to(DOCS_DIR)} -> {SERVED_IMAGE.relative_to(DOCS_DIR)}")

    version = sha256_short(SERVED_IMAGE)
    GENERATED_CSS.write_text(
        "/* Generated by docs/scripts/update_home_hero.py. Do not edit by hand. */\n"
        ".ap-home-hero-image {\n"
        f'    background-image: url("home/ap_pic_het_3d_hero.png?v={version}");\n'
        "}\n"
        "\n"
        "body::after {\n"
        f'    content: url("home/ap_pic_het_3d_hero.png?v={version}");\n'
        "    display: none;\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"[home hero] version {version}")


if __name__ == "__main__":
    main()
